name: Team 1 Project12



on:

  commit:
    
    branches: [ master ]	

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]



jobs:



  build:



    runs-on: ubuntu-latest



    steps:

    - uses: actions/checkout@v2

    

    - name: Build the API Docker image

      run: |

        docker build -t projec12api . 

          

    - name: Launch the servers using docker compose

      #env:

        #SLACK_URL: ${{ secrets.SLACK_URL_DEV }}

      run: |

        docker-compose up -d 

   

    - name: Verify that the correct containers are running 

      run: docker ps 



    - name: Run the API test suite

      run: |

	python ./apiTester.py --port 80 --host localhost



    - name: Push the new image to Docker Hub

      run: |

        docker login -u ${{ secrets.dockernewbie12 }} -p ${{ secrets.DeadLog_12!gh }}

        docker image tag project12api dockernewbie12/project12api:latest

        docker image push dockernewbie12/project12api:latest
