name: Team 1 Project12



on:

  workflow_dispatch:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]



jobs:



  build:



    runs-on: ubuntu-latest



    steps:

    - uses: actions/checkout@v2

    

    - name: Build the API Docker image

      run: |
        docker build -t projec12api . 

          

    - name: Launch the servers using docker compose


      run: |
        docker-compose up -d 

   

    - name: Verify that the correct containers are running 

      run: |
        docker ps 

    - name: Install Python
      
      run: |
        sudo apt-get install python3

    - name: Run the API test suite

      run: |
        python3 apiTester.py 


    - name: Push the new image to Docker Hub

      run: |

        docker login -u ${{ secrets.dockernewbie12 }} -p ${{ secrets.DeadLog_12gh }}

        docker image tag project12api dockernewbie12/project12api:latest

        docker image push dockernewbie12/project12api:latest
